#!/usr/bin/env ansible-playbook
---
- hosts: app
  tasks:
    - name: Create required directory
      file: 
        path: /usr/local/jconf
        state: directory
        mode: '0755'

    - name: rendering app config
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: config/docker-compose.yml.j2
          dest: /usr/local/jconf/docker-compose.yml
        # - src: config/dotenv.j2
        #   dest: /usr/local/jconf/.env

    - name: Run `docker-compose up` again
      docker_compose:
        project_src: /usr/local/jconf
        build: false
      register: output

    - debug:
        var: output