#!/usr/bin/env ansible-playbook
---
- hosts: app
  tasks:
    - name: Removing default docker packages
      apt: 
        pkg:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
        state: absent

    - name: Installing required packages
      apt: 
        pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Create required directory
      file: 
        path: /etc/apt/keyrings
        state: directory

    - name: Adding Docker's official GPG key
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Setting docker repo
      shell: |
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
        $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

    - name: Installing docker
      apt: 
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        - python3-pip
        update-cache: yes

    - name: Install Docker SDK for Python
      pip:
        name: 
        - docker
        - docker-compose